#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libXxf86misc
Version  : 1.0.4
Release  : 2
URL      : https://www.x.org/releases/individual/lib/libXxf86misc-1.0.4.tar.gz
Source0  : https://www.x.org/releases/individual/lib/libXxf86misc-1.0.4.tar.gz
Summary  : XFree86 Misc Extension Library
Group    : Development/Tools
License  : MIT
Requires: libXxf86misc-lib
Requires: libXxf86misc-license
Requires: libXxf86misc-man
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xextproto)
BuildRequires : pkgconfig(xf86miscproto)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)

%description
libXxf86misc - Extension library for the XFree86-Misc X extension.
All questions regarding this software should be directed at the
Xorg mailing list:

%package dev
Summary: dev components for the libXxf86misc package.
Group: Development
Requires: libXxf86misc-lib
Provides: libXxf86misc-devel

%description dev
dev components for the libXxf86misc package.


%package lib
Summary: lib components for the libXxf86misc package.
Group: Libraries
Requires: libXxf86misc-license

%description lib
lib components for the libXxf86misc package.


%package license
Summary: license components for the libXxf86misc package.
Group: Default

%description license
license components for the libXxf86misc package.


%package man
Summary: man components for the libXxf86misc package.
Group: Default

%description man
man components for the libXxf86misc package.


%prep
%setup -q -n libXxf86misc-1.0.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1531975646
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1531975646
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/libXxf86misc
cp COPYING %{buildroot}/usr/share/doc/libXxf86misc/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/lib64/libXxf86misc.so
/usr/lib64/pkgconfig/xxf86misc.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libXxf86misc.so.1
/usr/lib64/libXxf86misc.so.1.1.0

%files license
%defattr(-,root,root,-)
/usr/share/doc/libXxf86misc/COPYING

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/XF86Misc.3
/usr/share/man/man3/XF86MiscGetKbdSettings.3
/usr/share/man/man3/XF86MiscGetMouseSettings.3
/usr/share/man/man3/XF86MiscGetSaver.3
/usr/share/man/man3/XF86MiscQueryExtension.3
/usr/share/man/man3/XF86MiscQueryVersion.3
/usr/share/man/man3/XF86MiscSetKbdSettings.3
/usr/share/man/man3/XF86MiscSetMouseSettings.3
/usr/share/man/man3/XF86MiscSetSaver.3
