#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x4C09DD83CAAA50B2 (ajax@nwnk.net)
#
Name     : libXxf86misc
Version  : 1.0.4
Release  : 3
URL      : https://www.x.org/releases/individual/lib/libXxf86misc-1.0.4.tar.gz
Source0  : https://www.x.org/releases/individual/lib/libXxf86misc-1.0.4.tar.gz
Source1  : https://www.x.org/releases/individual/lib/libXxf86misc-1.0.4.tar.gz.sig
Summary  : XFree86 Misc Extension Library
Group    : Development/Tools
License  : MIT
Requires: libXxf86misc-lib = %{version}-%{release}
Requires: libXxf86misc-license = %{version}-%{release}
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xextproto)
BuildRequires : pkgconfig(xf86miscproto)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)

%description
libXxf86misc - Extension library for the XFree86-Misc X extension.
All questions regarding this software should be directed at the
Xorg mailing list:

%package dev
Summary: dev components for the libXxf86misc package.
Group: Development
Requires: libXxf86misc-lib = %{version}-%{release}
Provides: libXxf86misc-devel = %{version}-%{release}
Requires: libXxf86misc = %{version}-%{release}

%description dev
dev components for the libXxf86misc package.


%package lib
Summary: lib components for the libXxf86misc package.
Group: Libraries
Requires: libXxf86misc-license = %{version}-%{release}

%description lib
lib components for the libXxf86misc package.


%package license
Summary: license components for the libXxf86misc package.
Group: Default

%description license
license components for the libXxf86misc package.


%prep
%setup -q -n libXxf86misc-1.0.4
cd %{_builddir}/libXxf86misc-1.0.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604353581
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1604353581
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libXxf86misc
cp %{_builddir}/libXxf86misc-1.0.4/COPYING %{buildroot}/usr/share/package-licenses/libXxf86misc/bd7af2c6b4ce17526773bb20f616fe9f50c334f1
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/lib64/libXxf86misc.so
/usr/lib64/pkgconfig/xxf86misc.pc
/usr/share/man/man3/XF86Misc.3
/usr/share/man/man3/XF86MiscGetKbdSettings.3
/usr/share/man/man3/XF86MiscGetMouseSettings.3
/usr/share/man/man3/XF86MiscGetSaver.3
/usr/share/man/man3/XF86MiscQueryExtension.3
/usr/share/man/man3/XF86MiscQueryVersion.3
/usr/share/man/man3/XF86MiscSetKbdSettings.3
/usr/share/man/man3/XF86MiscSetMouseSettings.3
/usr/share/man/man3/XF86MiscSetSaver.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/libXxf86misc.so.1
/usr/lib64/libXxf86misc.so.1.1.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libXxf86misc/bd7af2c6b4ce17526773bb20f616fe9f50c334f1
